import type { Metadata } from "next";
import "../../globals.css";
import { ThemeProvider } from "@/app/_providers/theme-provider";
import { getStoreInitialSettings } from "@/lib/api/store/store-main-settings";
import { Toaster } from "sonner";
import { UserInitializer } from "@/app/_providers/user-init-provider";
import { UserWrapper } from "@/app/_providers/user-wrapper";

export const metadata: Metadata = {
  title: "Store template",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { storeTheme } = await getStoreInitialSettings();

  return (
    <html lang="uk" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme={storeTheme.alias}
          disableTransitionOnChange
        >
          <UserInitializer />
          <Toaster richColors position="top-center" />
          <UserWrapper>{children}</UserWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
