import type { Metadata } from "next";
import "../../globals.css";
import { ThemeProvider } from "@/app/_providers/theme-provider";
import { getStoreInitialSettings } from "@/lib/api/store/store-main-settings";
import { Toaster } from "sonner";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AdminSidebar } from "@/app/_components/Admin/AdminSidebar";
import { UserInitializer } from "@/app/_providers/user-init-provider";
import AdminHeader from "@/app/_components/Admin/Header/AdminHeader";

export const metadata: Metadata = {
  title: "Store template",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { storeTheme } = await getStoreInitialSettings();

  return (
    <html lang="uk" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme={storeTheme.alias}
          disableTransitionOnChange
        >
          <Toaster richColors position="top-center" />
          <UserInitializer />

          <SidebarProvider>
            <AdminSidebar />
            <SidebarInset>
              <AdminHeader />
              {children}
            </SidebarInset>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
