import type { Metadata } from "next";
import "./globals.css";

import { getStoreInitialSettings } from "@/lib/api/store/store-main-settings";
import Header from "@/app/_components/Header/Header";
import Footer from "@/app/_components/Footer/Footer";

export const metadata: Metadata = {
  title: "Store template",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const storeInitialSettings = await getStoreInitialSettings();
  return (
    <html lang="uk" className={storeInitialSettings.storeTheme.alias}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
